export const enUS = {
    translation: {
        indexPage: "Home",
        cskb: "Knowledge Base",
        moreProjects: "More Projects",
        welcomeAccess: "Welcome to",
        corona_studio: "",
        weDevelop: "We Develop",
        whoWeAre: "Who We Are",
        whoWeAreDetail:
            "Corona Studio originated from the CMFL development team. We are a computer development team of enthusiasts and professionals focused on Minecraft.",
        ourProjects: "Our Projects",

        lxDescription: "LauncherX is a next-gen, powerful, and visually appealing Minecraft launcher by Corona Studio.",
        projbobcatDescription:
            "A next-gen Minecraft launcher core written in C#, offering the most freedom, speed, and completeness.",
        connectxDescription:
            "A high-performance cross-platform MC multiplayer module in C#, supporting P2P and relay features.",
        cskbDescription: "CSKB is our open knowledge base for all MC players and Corona Studio-related projects.",
        hiveDescription:
            "A high-performance cross-platform network library in C#, supporting TCP, UDP, KCP, and other protocols.",

        lxSlogan: "A next-gen Minecraft launcher with powerful features and a sleek UI.",
        downloadNow: "Download Now",
        powerfulFeatures: "Powerful Features",
        powerfulFeaturesDescription:
            "Offers a variety of practical and powerful functions for managing all your game resources in one place.",
        notOnly: "Not just",

        modPackInstallation: "Modpack Installation",
        resourceDownload: "Resource Download",
        versionManagement: "Version Management",
        serverManagement: "Server Management",
        modPackManagement: "Modpack Management",
        accountManagement: "Account Management",

        aggressiveOptimizing: "Extreme Optimization",
        aggressiveOptimizingDescription:
            "LauncherX adopts the latest development technologies, featuring multi-task scheduling and segmented downloads/resumable transfers for an optimal experience.",

        alwaysGetLatestUpdates: "Always Get the Latest Updates",
        alwaysGetLatestUpdatesDescription:
            "Our team provides periodic stable updates while offering the latest features and improvements in beta. Switching to insider builds lets you experience our newest developments and help us refine LauncherX.",

        bugFixRequiredTime: "Bug Fix Time",
        updateFrequency: "Update Frequency",
        featureDevelopment: "Feature Development",
        feedbackResponse: "Feedback Response",

        acquire: "Acquire",
        download: "Download",

        integratedWithThirdPartyResources: "Integrated with Third-Party Resources",
        integratedWithThirdPartyResourcesDescription:
            "LauncherX integrates with third-party sites like CurseForge and Modrinth to provide the latest mods, resource packs, and plugins.",

        joinServer: "Join Server",
        serverList: "Server List",
        beginningOfEverything: "The Beginning of Everything...",
        beginningOfEverythingDescription1:
            "CraftMineFun was our starting point: from the first MC server CMF to the launcher CMFL built for it...",
        beginningOfEverythingDescription2:
            "Now, LauncherX—reborn from CMFL—has emerged, and our former game server has reopened as CMFS.",

        event1: "The Start",
        event1Description: "The CMF team was formed, launching the CraftMineFun server.",
        event2: "Expanding Horizons",
        event2Description:
            "To meet growing needs, CMFL was developed as a dedicated launcher for CMF, using KMCCC as its core.",
        event3: "A New Beginning",
        event3Description: "CMFL was officially released.",
        event4: "The Battle Continues",
        event4Description:
            "CMFL received its biggest UI update yet. Later that year, the team rebranded as Corona Studio and began open recruitment.",
        event5: "Pushing Forward",
        event5Description:
            "The self-developed open-source launcher core ProjBobcat was released, and CMFL transitioned to it. A complete CMFL overhaul was also planned.",
        event6: "Starting Anew",
        event6Description:
            "LauncherX was announced. Group server management was handed over, with CMFS-Pure launching first. Internal testing began later that year.",
        event7: "Back on Track?",
        event7Description:
            "CMFS held a New Year event. Mid-year, a new website was planned. LauncherX began closed beta.",
        event8: "A Fresh Start",
        event8Description:
            "CMFS relaunched with new mod servers. In late October, the new website went live. In November, LauncherX entered public beta.",
        event9: "The Story Continues",
        event9Description: "History is still being written...",

        login: "Login",
        pleaseInputEmail: "Enter Email",
        pleaseInputPassword: "Enter Password",
        pleaseInputUserName: "Enter Username",
        confirmPassword: "Confirm Password",

        submit: "Submit",
        register: "Register",
        forgetPassword: "Forgot",
        resetPassword: "Reset Password",
        confirmEmail: "Confirm Email",
        confirmEmailDetail: "Verifying registration status for [{}]...",
        onlyAllowedChars: "Hint: Only these half-width special characters allowed in password: ",

        emailVerified: "Email Verified",
        emailVerifiedDescription: "Verification successful, redirecting to login page...",
        emailVerificationFailed: "Email Verification Failed",
        emailVerificationFailedDescription: "Verification failed due to missing parameters, returning to home...",
        emailVerificationExpired: "Invalid or expired link. Please request a new one.",
        emailVerificationNotFound: "Credential not found. This may not be a valid link.",

        resetPasswordLinkInvalid: "Invalid Reset Password Link",
        resetPasswordLinkInvalidDescription: "Invalid link due to missing parameters, returning to home...",

        rememberPassword: "Remember Password",

        email: "Email",
        username: "Username",
        userId: "User ID",

        emailRequired: "Email is required",
        emailIncorrectMessage: "Invalid email, please enter a valid address.",
        usernameRequired: "Username is required",
        usernameRuleDescription:
            "Username must be 6-18 characters, allowing letters, hyphens, underscores, and numbers.",
        passwordRequired: "Password is required",
        passwordRuleDescription:
            "Password must be at least 8 characters with uppercase, lowercase, number, and symbol.",
        passwordIsNotSame: "Passwords do not match",

        userCenter: "User Center",
        deviceManage: "Device Management",
        sponsor: "Sponsor",

        userHomeTip1Title: "Secure Your Account",
        userHomeTip1Description: "Keep your account safe. Do not share sensitive information.",
        userHomeTip2Title: "Become a Sponsor",
        userHomeTip2Description:
            "Interested in our latest developments? After sponsoring us on AFDian, enter your order number in the sponsor menu to get access!",

        deviceId: "Device ID",
        serialNumber: "Serial Number",

        afdCardTitle: "Sponsor Us on AFDian",
        afdCardDescription: "Sponsor us on AFDian to join our beta program!",
        minebbsCardTitle: "Check Our Promo Post",
        minebbsCardDescription: "Visit our MineBBS post to leave feedback!",

        afdOrderNumber: "AFDian Order Number",
        afdOrderNumberRequired: "Order number is required",
        afdOrderNumberRuleDescription: "AFDian order numbers are 27-digit numeric sequences.",

        goto: "Go to",

        unknownError: "Unknown Error",
        unknownLoginErrorDescription: "Unknown login error. Please contact admin.",
        incorrectEmailOrPassword: "Incorrect email or password",
        loginFailed: "Login Failed",
        loginSucceeded: "Login Successful",
        loginSucceededDescription: "Login successful, redirecting to user center...",

        emailOrUsernameUsed: "Email or username already in use",
        backendServerError: "Backend server error, please contact admin",
        registerFailed: "Registration Failed",
        registerSucceeded: "Registration Successful",
        registerSucceededDescription: "Successfully registered, redirecting to login page...",

        forgetPasswordReqSucceeded: "Password Reset Requested",
        forgetPasswordReqSucceededDescription: "If your email matches our records, you'll receive a reset link!",
        forgetPasswordReqFailed: "An unknown error occurred while requesting a password reset. Contact admin.",

        logout: "Logout",
        loggedOut: "Logged Out",
        loggedOutDescription: "Logged out successfully, returning to home...",

        userInfoFetchFailed: "Failed to Retrieve User Info",
        userInfoFetchFailedDescription: "Could not fetch user info. Try logging out and back in.",

        userDeviceFetchFailed: "Failed to Retrieve Devices",
        userDeviceFetchFailedDescription: "No device info found. Try logging out and back in.",

        userBranch: "User Branch",
        userChannel: "User Channel",

        stable: "Stable",
        preview: "Preview",

        buildManagement: "Build Management",
        userManagement: "User Management",
        userManagementDescription: "Find accounts, review their status, and manage access identities in one place.",
        accountDirectory: "Account Directory",
        allUserAccounts: "All Accounts",
        searchResults: "Search Results",
        totalUsers: "Total users",
        matchingUsers: "Matching users",
        copyUserId: "Copy user ID",
        userIdCopied: "User ID Copied",
        managedUserCount: "{{count}} users",
        searchUsers: "Search username, email, or user ID",
        userAccount: "User Account",
        accountStatus: "Account Status",
        emailUnverified: "Email Unverified",
        accountLocked: "Locked",
        userIdentity: "User Identity",
        unnamedUser: "Unnamed user",
        noUsers: "No matching users",
        userListLoadFailed: "Failed to Load Users",
        userListLoadFailedDescription: "Could not retrieve users. Check your connection and administrator access.",
        userRoleUser: "User",
        userRoleReader: "Read-only Member",
        userRoleReviewer: "Build Reviewer",
        userRoleProjectManager: "Project Manager",
        userRoleAdmin: "Administrator",
        confirmUserRoleChange: "Change this user's identity?",
        confirmUserRoleChangeDescription: "Change {{user}} to {{role}}.",
        userRoleTokenNotice:
            "Previously issued tokens may retain old permissions. Ask the user to sign in again to receive the new identity.",
        userRoleUpdateSucceeded: "User Identity Updated",
        userRoleUpdateSucceededDescription: "The identity for {{user}} has been updated.",
        userRoleUpdateFailed: "Failed to Update User Identity",
        userRoleUpdateFailedDescription: "Could not update this user's identity. Please try again.",
        userRoleProtectedDescription: "The active administrator or the system's last administrator cannot be demoted.",
        notificationManagement: "Launcher Notifications",
        notificationManagementDescription:
            "Create, edit, and delete LauncherX notifications. Saving refreshes the server cache immediately.",
        notificationCount: "{{count}} notifications",
        searchNotifications: "Search title, content, or author",
        notification: "Notification",
        notificationAuthor: "Author",
        publishDate: "Published",
        createNotification: "Create Notification",
        editNotification: "Edit Notification",
        edit: "Edit",
        notificationTitle: "Notification Title",
        notificationContent: "Notification Content",
        noNotifications: "No notifications",
        fieldRequired: "This field is required.",
        notificationListLoadFailed: "Failed to Load Notifications",
        notificationListLoadFailedDescription:
            "Could not retrieve notifications. Check your connection and administrator access.",
        notificationSaveSucceeded: "Notification Saved",
        notificationCreatedDescription: "The notification was created and is immediately available to launchers.",
        notificationUpdatedDescription: "The notification was updated and is immediately available to launchers.",
        notificationSaveFailed: "Failed to Save Notification",
        notificationSaveFailedDescription: "Could not save the notification. Check its content and try again.",
        confirmDeleteNotification: "Delete this notification?",
        confirmDeleteNotificationDescription: 'Notification "{{title}}" will be permanently deleted.',
        notificationDeleteSucceeded: "Notification Deleted",
        notificationDeleteSucceededDescription: "The notification was deleted and the launcher cache was refreshed.",
        notificationDeleteFailed: "Failed to Delete Notification",
        notificationDeleteFailedDescription: "Could not delete the notification. It may no longer exist.",
        contributionManagement: "Resource Contributions",
        contributionReview: "Contribution Review",
        contributionManagementDescription:
            "Review third-party resource translations, links, tags, and ratings submitted by LauncherX users, then publish an approved resource.",
        pendingContributionList: "Pending Resources",
        pendingContributionCount: "{{count}} pending resources",
        pendingResources: "Pending resources",
        totalSubmissions: "Total submissions",
        ratedResources: "Rated resources",
        contributionResource: "Resource",
        submissionCount: "Contributions",
        userRating: "User rating",
        noRating: "No rating",
        notTranslated: "Not translated",
        actions: "Actions",
        review: "Review",
        searchContributions: "Search name, translation, or ID",
        noPendingContributions: "No pending contributions",
        contributionListLoadFailed: "Failed to Load Contributions",
        contributionListLoadFailedDescription:
            "Could not retrieve pending contributions. Check your connection and administrator access.",
        contributionDetail: "Contribution Details",
        contributionDetailLoadFailed: "Failed to Load Contribution Details",
        contributionDetailLoadFailedDescription:
            "Could not retrieve contribution details. Check your connection and administrator access.",
        contributionNotFound: "This pending resource does not exist or has already been processed.",
        backToContributionList: "Back to Contributions",
        resourceId: "Resource ID",
        contributor: "Contributor",
        suggestedTranslation: "Suggested translation",
        contributedLink: "Contributed link",
        contributedTag: "Contributed tag",
        translationContributions: "Translation Contributions",
        translationContributionDescription:
            "Review suggested translations, remove invalid entries, or ban abusive contributors.",
        linkContributions: "Link Contributions",
        tagContributions: "Tag Contributions",
        ratingContributions: "Rating Records",
        noTranslationContributions: "No translation contributions",
        noLinkContributions: "No link contributions",
        noTagContributions: "No tag contributions",
        noRatingContributions: "No rating records",
        delete: "Delete",
        banUser: "Ban user",
        confirmDeleteContribution: "Delete this contribution?",
        confirmDeleteContributionDescription: "Contribution {{id}} will be permanently deleted. This cannot be undone.",
        deleteContributionSucceeded: "Contribution Deleted",
        deleteContributionSucceededDescription: "The contribution was removed from the pending resource.",
        deleteContributionFailed: "Failed to Delete Contribution",
        deleteContributionFailedDescription: "The contribution could not be deleted. It may no longer exist.",
        confirmBanUser: "Ban this user?",
        confirmBanUserDescription: "User {{user}} will no longer be able to submit third-party resource contributions.",
        banUserSucceeded: "User Banned",
        banUserSucceededDescription: "User {{user}} has been banned.",
        banUserFailed: "Failed to Ban User",
        banUserFailedDescription: "The user could not be banned. Please try again.",
        userAlreadyBanned: "This user is already banned.",
        finalResourceInformation: "Final Resource Information",
        finalResourceInformationDescription:
            "Confirm the final translation, link, and tags. Publishing creates an official resource, records its contributors, and clears all pending records for this resource.",
        finalTranslatedName: "Final translated name",
        finalResourceLink: "Final resource link",
        finalResourceTags: "Final resource tags",
        resourceTagsPlaceholder: "Separate tags with commas",
        translatedNameRequired: "Enter the final translated name.",
        resourceLinkRequired: "Enter the final resource link.",
        resourceLinkInvalid: "Enter a valid HTTP or HTTPS URL.",
        resourceTagsRequired: "Enter at least one tag.",
        clear: "Clear",
        acceptAsOfficialResource: "Publish as Official Resource",
        confirmAcceptContribution: "Publish this resource?",
        confirmAcceptContributionDescription:
            "This creates an official resource, records all related contributors, and deletes every pending submission and rating for the resource. This cannot be undone.",
        acceptContributionSucceeded: "Contribution Approved",
        acceptContributionSucceededDescription: "The pending information was published as an official resource.",
        acceptContributionFailed: "Failed to Approve Contribution",
        acceptContributionFailedDescription:
            "The contribution could not be published. Confirm that the pending resource still exists and try again.",
        buildManagementDescription:
            "Only builds with Push to users enabled are loaded into the server build cache. Refresh the cache after making changes.",
        allBuilds: "All Builds",
        buildCount: "{{count}} builds",
        buildInfo: "Build",
        buildTarget: "Target",
        buildStatus: "Status",
        pushEnabledBuilds: "Delivery enabled",
        cachedBuilds: "Currently cached",
        searchBuilds: "Search branch, framework, or runtime",
        noMatchingBuilds: "No matching builds",
        releaseDate: "Release Date",
        buildBranch: "Branch",
        buildChannel: "Channel",
        buildFramework: "Framework",
        buildRuntime: "Runtime",
        buildReviewStatus: "Review Status",
        buildApproved: "Approved",
        buildRejected: "Rejected",
        buildUnreviewed: "Unreviewed",
        buildCacheStatus: "Cache Status",
        buildCached: "Cached",
        buildNotCached: "Not Cached",
        pushToUsers: "Push to users",
        enabled: "Enabled",
        disabled: "Disabled",
        refreshBuildCacheNow: "Refresh cache",
        buildUpdateSucceeded: "Build Updated",
        buildEnabledDescription: "The build is marked for delivery. Refresh the build cache to apply it.",
        buildDisabledDescription: "The build is no longer marked for delivery. Refresh the build cache to apply it.",
        buildUpdateFailed: "Build Update Failed",
        buildUpdateFailedDescription: "Could not update the build. Please try again.",
        buildNoLongerExists: "This build was replaced or removed. The list has been refreshed; please select it again.",
        buildCacheRefreshSucceeded: "Build Cache Refreshed",
        buildCacheRefreshSucceededDescription: "The cache now contains {{count}} deliverable builds.",
        buildCacheRefreshFailed: "Build Cache Refresh Failed",
        buildCacheRefreshFailedDescription: "Could not refresh the build cache. Please try again.",

        deviceRemoved: "Device Removed",
        deviceRemoveFailed: "Device Removal Failed",
        deviceRemoveFailedDescription: "Could not remove device. Please try again later.",

        howToCheckSponsorOrderNumber: "How to Find Your Sponsor Order Number?",
        checkHere: "Check Here",
        checkHereLink: "https://kb.corona.studio/enUS/guide/general/donate.html",
        sponsorThanks: "Thank You for Your Support!",
        noRecommendedBuild: "No Recommended Build",
        failedToLoadBuildsDescription: "Failed to load build list. Please check your network connection.",
        failedToLoadBuilds: "Failed to load build list.",
        retry: "Retry",
        downloadThanks: "Thank You for Downloading",
        downloadThanksDescription:
            "Your download should have started. Please refer to the setup guides below if you encounter issues.",
        downloadThanksFollowGuide: "Please follow the guide below to complete the installation.",
        setupGuides: "Setup Guides",
        recommendedGuide: "Recommended Guide",
        basedOnYourSystem: "Based on your system",
        weRecommendReading: "We recommend reading the following guide to complete the installation.",
        windowsSetupGuide: "Windows Setup Guide",
        macosSetupGuide: "macOS Setup Guide",
        linuxSetupGuide: "Linux Setup Guide",
        guideFor: "Guide for",
        viewGuide: "View Guide",
        revokeCsAccountTitle: "Complete delete Corona Studio account and related data",
        revokeCsAccountMessage:
            "This operation will delete all the data related to you, including your account info, device info, sponsor info, friend relations. This operation can not be reverted, do with extra caution!",
        logoutAndDelete: "Logout and delete",

        confirmDelete: "Confirm Delete?",
        deleteAccountFailed: "Failed to delete account.",
        deleteAccountFailedDescription1:
            "Failed to delete account, session token has been revoked, please re-login and try again later. If issue persist, please contact admin.",
        deleteAccountFailedDescription2:
            "Failed to delete account, please try again later. If issue persist, please contact admin. Might be backend error.",

        deleteAccountSucceeded: "Account deleted.",
        deleteAccountSucceededDescription:
            "Account deleted, all the info has been deleted. You can not use any service anymore.",

        sponsorBadgeText: "Sponsor",
        talkIsCheap: "Talk is cheap"
    }
};
