export const zhCN = {
    translation: {
        themeSettings: "主题设置",
        themeLight: "浅色",
        themeDark: "深色",
        themeSystem: "跟随系统",
        dashboardTitle: "管理概览",
        dashboardSubtitle: "查看账户、登录安全与内容运营数据",
        dashboardDays: "近 {{count}} 天",
        dashboardRefresh: "刷新数据",
        dashboardUpdated: "更新于 {{time}} · 统计时区：{{zone}}",
        dashboardAllTime: "当前总量",
        dashboardPeriod: "所选时间范围内",
        dashboardLoginTrend: "登录趋势",
        dashboardLoginNote: "按日统计登录尝试，包含今日；缺失日期补零",
        dashboardSucceeded: "成功",
        dashboardFailed: "失败",
        dashboardAccounts: "账户构成",
        dashboardBuilds: "构建运行平台",
        dashboardBuildNote: "当前保留的全部构建，包含未发布构建",
        dashboardPending: "待审贡献",
        dashboardPendingNote: "按贡献条目计数，同一资源可包含多个条目",
        dashboardNoData: "暂无数据",
        dashboardViewData: "查看图表数据",
        dashboardDate: "日期",
        dashboardCount: "数量",
        dashboardSuccessRate: "登录成功率",
        dashboardUsers: "注册用户",
        dashboardSponsors: "赞助用户",
        dashboardRegularUsers: "普通用户",
        dashboardQqVerified: "QQ 已验证用户",
        dashboardDevices: "绑定设备",
        dashboardLoginAttempts: "登录尝试",
        dashboardFailedLogins: "失败登录",
        dashboardPublishedBuilds: "已发布构建",
        dashboardPendingContributions: "待审贡献条目",
        dashboardAcceptedContributions: "已采纳贡献",
        dashboardNotifications: "通知",
        dashboardTranslations: "翻译",
        dashboardLinks: "链接",
        dashboardTags: "标签",
        dashboardUnknown: "未标注",

        indexPage: "主页",
        cskb: "知识库",
        moreProjects: "更多项目",
        welcomeAccess: "欢迎访问",
        corona_studio: "日冕工作室",
        weDevelop: "我们开发",
        whoWeAre: "我们是谁",
        whoWeAreDetail:
            "Corona Studio 源于 CMFL 开发组。我们是以 Minecraft 为业务核心的由爱好者和专业人士组成的计算机开发团队。",
        ourProjects: "我们的项目",

        lxDescription: "LauncherX 是由日冕工作室开发的下一代功能强大、界面美观 MineCraft 启动器。",
        projbobcatDescription: "基于 C# 编写的下一代 Minecraft 启动器核心，提供最自由、最快速和最完整的体验。",
        connectxDescription: "基于 C# 开发的高性能跨平台 MC 联机模块实现，支持 P2P 和 中继 等高级特性。",
        cskbDescription: "CSKB 是我们面向所有 MC 玩家与日冕工作室相关项目的公开知识库。",
        hiveDescription: "基于 C# 开发的高性能跨平台网络库实现，支持包括 TCP，UDP，KCP 等主流协议栈。",

        lxSlogan: "功能强大、界面优美的下一代 MineCraft 启动器。",
        downloadNow: "立即下载",
        powerfulFeatures: "强大的功能",
        powerfulFeaturesDescription: "提供大量实用强大的功能，一站式管理你的所有游戏资源。",
        notOnly: "不仅仅是",

        modPackInstallation: "模组包安装",
        resourceDownload: "资源下载",
        versionManagement: "版本管理",
        serverManagement: "服务器管理",
        modPackManagement: "模组包管理",
        accountManagement: "账户管理",

        aggressiveOptimizing: "极致的优化",
        aggressiveOptimizingDescription:
            "LauncherX 始终与时俱进，始终同步到最新的开发技术，借助这些技术，我们得以更好地设计多任务调度和分片下载/断点续传等功能。这些精心打造的功能可以最大程度保证您的浏览和安装体验。",

        alwaysGetLatestUpdates: "始终获取最新更新",
        alwaysGetLatestUpdatesDescription:
            "我们的开发团队在提供对稳定版的不定期更新时，也会在测试版中提供最新的功能和改进。通过切换到内部测试版本即可获取团队最新的开发进度和体验最新的功能，同时也可以帮助我们更好的改进和完善 LauncherX。",

        bugFixRequiredTime: "修复 Bug 所需时间",
        updateFrequency: "更新频率",
        featureDevelopment: "功能开发",
        feedbackResponse: "反馈响应",

        acquire: "获取",
        download: "下载",

        integratedWithThirdPartyResources: "与第三方资源集成",
        integratedWithThirdPartyResourcesDescription:
            "LauncherX 与 CurseForge、Modrinth 等第三方资源站点集成，为您提供最新的模组包、资源包、插件等资源。",

        joinServer: "加入服务器",
        serverList: "服务器列表",
        beginningOfEverything: "一切的起点...",
        beginningOfEverythingDescription1:
            "CraftMineFun 是我们的一切的起点：从第一个 MC 游戏服务器 CMF 开始，到面向这个服务器的启动器 CMFL...",
        beginningOfEverythingDescription2:
            "如今，脱胎换骨自CMFL的下一代启动器 LauncherX 已然问世，曾经的游戏群组服已经以 CMFS 的全新姿态重新开放",

        event1: "屁屁，启动!",
        event1Description: "CMF 团队成立，开始运营游戏服务器 CraftMineFun。",
        event2: "吔! 越走越宽",
        event2Description:
            "应实际需要，老腊肉开始筹备开发专用于 CMF 的游戏启动器 CraftMineFun Launcher，使用KMCCC作为核心。",
        event3: "欢迎新开始",
        event3Description: "CMFL 面世",
        event4: "战斗续行",
        event4Description:
            "CMFL 继续更新，并迎来了有史以来最大的 UI 更新。在此年下半年，团队更名为 Corona Studio（日冕工作室）并开始公开招募。",
        event5: "辗转前进",
        event5Description:
            "自研开源启动核心 ProjBobcat 公布，CMFL 转用 ProjBobcat 作为启动核心。下半年，CMFL 完全重构的更新立项。",
        event6: "另起炉灶",
        event6Description:
            "公布下一代游戏启动器 LauncherX。团队内的群组服由法棍接手管理，纯净生存服务器率先公开，命名为 CMFS-Pure。下半年开始内部人员测试。",
        event7: "重回正轨？",
        event7Description: "年初，CMFS 举行了新年拓荒活动。年中，决定制作新官网。同年，LauncherX 开始邀请内测。",
        event8: "新的起点",
        event8Description:
            "CMFS 在老腊肉的服务器上重新开放，并新增了 Mod 服。10月末，新官网上线。11月，LauncherX 正式开启公测。",
        event9: "故事继续",
        event9Description: "历史仍在书写...",

        login: "登录",
        pleaseInputEmail: "请输入邮箱",
        userNameOrEmail: "用户名或邮箱",
        pleaseInputPassword: "请输入密码",
        pleaseInputUserName: "请输入用户名",
        confirmPassword: "确认密码",

        submit: "提交",
        register: "注册",
        onlyAllowedChars: "提示: 密码中只允许下列半角特殊符号: ",

        rememberPassword: "记住密码",
        forgetPassword: "忘记密码",
        resetPassword: "重置密码",
        sendQqResetCode: "通过 QQ 获取邀请码",
        passwordResetRequestDescription:
            "提交用户名或旧账户邮箱后，机器人会向该账号通过 /verify 绑定的 QQ 私聊发送一次性邀请码。",
        passwordResetRequestAccepted: "请求已受理",
        passwordResetRequestAcceptedDescription:
            "如果账号存在、已完成验证并绑定 QQ，机器人会发送一次性邀请码，请检查 QQ 私聊。",
        passwordResetRequestFailed: "请求密码重置失败",
        passwordResetRequestFailedDescription: "暂时无法请求密码重置，请稍后再试。",
        passwordResetCodeDescription: "请输入机器人私聊发送的 6 位一次性邀请码和新密码。",
        pleaseInputResetCode: "请输入 6 位邀请码",
        resetCodeRequired: "邀请码不能为空",
        resetCodeRuleDescription: "邀请码必须是 6 位数字",
        invalidOrExpiredResetCode: "邀请码错误、已过期或尝试次数过多，请重新获取。",
        passwordResetSucceeded: "密码重置成功",
        passwordResetSucceededDescription: "新密码已生效，正在前往登录页面……",
        passwordResetFailed: "密码重置失败",
        passwordResetFailedDescription: "暂时无法重置密码，请稍后再试。",

        email: "邮箱",
        noEmail: "未设置邮箱",
        username: "用户名",
        userId: "用户 ID",

        emailRequired: "邮箱是必填项",
        emailIncorrectMessage: "邮箱不正确，请输入正确的邮箱",
        usernameRequired: "用户名是必填项",
        usernameRuleDescription: "用户名长度在 6-18 位，允许大小写字母、横线、下划线和数字",
        passwordRequired: "密码是必填项",
        passwordRuleDescription: "密码至少需要 8 位，包含至少一个大写，小写字母、数字和符号",
        passwordIsNotSame: "两次密码不一致",

        userCenter: "个人中心",
        deviceManage: "设备管理",
        sponsor: "赞助",

        userHomeTip1Title: "保护您的账号安全",
        userHomeTip1Description: "请注意您的账户安全，不要将敏感信息暴露给他人。",
        userHomeTip2Title: "成为赞助者",
        userHomeTip2Description:
            "对我们最新的开发成果感兴趣？在爱发电完成赞助后点击左侧的赞助菜单，输入您的爱发电订单号即可成为赞助者！",

        deviceId: "设备 ID",
        serialNumber: "序列号",

        afdCardTitle: "前往爱发电赞助我们",
        afdCardDescription: "前往爱发电赞助我们即可加入我们的内测计划！",
        minebbsCardTitle: "查看我们宣传贴",
        minebbsCardDescription: "快去 MineBBS 上的宣传贴给我们评价和反馈吧！",

        afdOrderNumber: "爱发电订单号",
        afdOrderNumberRequired: "爱发电订单号是必填项",
        afdOrderNumberRuleDescription: "爱发电的订单号应该是一串由纯数字组成的 23-30 位号码",

        goto: "前往",

        unknownError: "未知错误",
        unknownLoginErrorDescription: "未知的登陆错误，请尝试联系管理员。",
        incorrectEmailOrPassword: "错误的邮箱或密码",
        loginFailed: "登陆失败",
        loginSucceeded: "登陆成功",
        loginSucceededDescription: "成功登录，即将跳转至用户中心...",

        usernameUsed: "用户名已被占用",
        backendServerError: "后端服务器故障，请联系管理员",
        registerFailed: "注册失败",
        registerSucceeded: "注册成功",
        registerSucceededDescription: "账号已创建，请登录。付费用户需要完成 QQ 验证。",
        turnstileFailed: "人机验证失败或已过期，请重试。",
        turnstileUnavailable: "人机验证未配置，暂时无法注册。",
        registrationComplete: "注册完成",
        verificationCodeExpired: "验证码已过期。请返回登录页重新登录，申请新的验证码。",
        requestNewVerificationCode: "重新登录申请验证码",
        verificationRequired: "完成 QQ 机器人验证后即可登录",
        yourVerificationCode: "你的 6 位验证码（点击复制）",
        joinQqGroup: "加入任一 QQ 群",
        verificationStepJoin: "在 QQ 中搜索并加入上方任一群聊。",
        verificationStepPrivateChat: "在群内找到 Corona Studio 验证机器人，必要时先 @机器人。",
        verificationStepCommand: "向机器人发送命令：",
        verificationInfoMissing: "未找到注册验证码，请返回注册页面重新注册或联系管理员。",
        verifiedGoLogin: "我已完成验证，前往登录",
        accountNotVerified: "账号尚未验证，请加入 QQ 群并私聊机器人发送 /verify 验证码。",
        copied: "已复制",

        userLoginBanned: "已封禁登录",
        userOperations: "操作",
        resetUserAvatar: "重置头像",
        banUserLogin: "封禁登录",
        unbanUserLogin: "解除封禁",
        confirmResetUserAvatar: "将“{{user}}”的头像重置为新的随机头像？",
        confirmBanUserLogin: "封禁“{{user}}”后，该用户将无法登录，已有会话也无法继续访问。",
        confirmUnbanUserLogin: "解除“{{user}}”的登录封禁？用户可以重新登录。",
        userOperationSucceeded: "操作成功",
        userOperationFailed: "操作失败，请稍后重试。",
        userBanProtected: "不能封禁当前管理员或最后一个可用管理员。",
        loginBannedDescription: "此账号已被封禁，无法登录。如有疑问，请联系管理员。",

        userAvatar: "用户头像",
        avatarUnavailable: "暂无头像",
        changeAvatar: "修改头像",
        avatarCropDescription: "拖动图片调整位置，或使用方向键微调。缩放至合适大小后保存方形头像。",
        avatarSelect: "选择图片",
        avatarReselect: "重新选择图片",
        avatarFileHint: "支持 JPG、PNG、WebP，文件大小不超过 10 MB。",
        avatarInvalidFile: "请选择 10 MB 以内的有效 JPG、PNG 或 WebP 图片。",
        avatarCropArea: "裁剪区域（支持方向键调整）",
        avatarZoom: "缩放",
        avatarReset: "重置裁剪",
        avatarPreview: "头像预览",
        avatarOutputHint: "保存为 512 × 512 的方形 PNG，头像以圆形显示。",
        avatarCancel: "取消",
        avatarSave: "保存头像",
        avatarUploadFailed: "头像上传失败，请稍后重试。",
        avatarUpdated: "头像已更新",

        logout: "注销",
        loggedOut: "成功注销",
        loggedOutDescription: "成功注销，即将返回主页...",

        userInfoFetchFailed: "无法获取用户信息",
        userInfoFetchFailedDescription: "无法获取用户信息，请尝试注销后重新登录",

        userDeviceFetchFailed: "无法获取已经注册的设备信息",
        userDeviceFetchFailedDescription: "没有获取到设备信息，请尝试注销后重新登录",

        userBranch: "用户分支",
        userChannel: "用户通道",

        stable: "稳定通道",
        preview: "测试通道",

        deviceRemoved: "成功删除设备",
        deviceRemoveFailed: "删除设备失败",
        deviceRemoveFailedDescription: "无法删除设备，请稍候再次尝试...",

        howToCheckSponsorOrderNumber: "如何查看赞助时的订单号？",
        checkHere: "查看这里",
        checkHereLink: "https://kb.corona.studio/zhCN/guide/general/donate.html",
        sponsorThanks: "感谢您的赞助！",
        sponsorThanksDescription:
            "感谢您对日冕工作室的支持！我们会继续改进我们的产品并取得更大的进步，我们今天的成就离不开每一位赞助者的贡献。",
        sponsorInsiderGroupTitle: "内测群",
        sponsorInsiderGroupDescription: "加入内测群，获取最新的更新通知。点击群号即可复制。",
        sponsorQqVerificationTitle: "完成 QQ 账号验证",
        sponsorQqVerificationDescription: "订单已核销。请在 QQ 群内发送验证命令，绑定您的 Corona Studio 账号。",
        sponsorQqVerificationDone: "我已发送验证命令，检查验证状态",
        sponsorQqVerificationRefresh: "刷新验证码",
        sponsorQqVerificationExpired: "验证码已过期，请刷新后再发送验证命令。",
        sponsorQqVerificationLoginHint: "验证码暂时无法在此显示。请重新登录，按登录页的提示获取验证码并完成 QQ 验证。",
        sponsorQqVerificationLogin: "重新登录获取验证码",
        failedToGetIsPaid: "无法获取赞助状态",
        failedToGetIsPaidDescription: "无法获取赞助状态，可能是服务器错误",

        userNotFound: "用户未找到",
        userAlreadySponsor: "您已经赞助过啦！该功能只能使用一次！",
        redeemAlreadyUsedOrInvalid: "这个订单号已被兑换或是无效的订单号，请检查后再次尝试",

        errorBoundaryTitle: "似乎到了世界的边缘...",
        errorBoundarySubText: '"早安！若无缘再见，便祝你午安，晚安，夜夜好梦。"',

        adminCenter: "管理中心",
        returnToUserCenter: "返回用户中心",

        userCount: "用户数",
        userCountDescription: "已注册日冕账号的用户数量",
        insiderUserCount: "内测用户数",
        insiderUserCountDescription: "加入赞助计划的用户数量",
        loginCount: "登陆总计",
        loginCountDescription: "在过去 24H 的登陆数量",
        failedLoginCount: "失败的登陆尝试",
        failedLoginCountDescription: "在过去 24H 失败的登陆数量",

        sponsorAdmin: "赞助者管理",
        buildManagement: "构建管理",
        userManagement: "用户管理",
        userManagementDescription: "快速查找账户、核对状态，并集中管理用户的访问身份。",
        accountDirectory: "账户目录",
        allUserAccounts: "全部账户",
        searchResults: "搜索结果",
        totalUsers: "用户总数",
        matchingUsers: "匹配用户",
        copyUserId: "复制用户 ID",
        userIdCopied: "用户 ID 已复制",
        managedUserCount: "共 {{count}} 个用户",
        searchUsers: "搜索用户名、邮箱或用户 ID",
        userAccount: "用户账户",
        accountStatus: "账户状态",
        qqVerified: "QQ 已验证",
        qqUnverified: "QQ 未验证",
        accountLocked: "已锁定",
        userIdentity: "用户身份",
        unnamedUser: "未命名用户",
        noUsers: "没有符合条件的用户",
        userListLoadFailed: "加载用户失败",
        userListLoadFailedDescription: "无法获取用户列表，请检查网络连接或管理员权限。",
        userRoleUser: "普通用户",
        userRoleReader: "只读成员",
        userRoleReviewer: "构建审核员",
        userRoleProjectManager: "项目管理员",
        userRoleAdmin: "管理员",
        confirmUserRoleChange: "确认切换用户身份？",
        confirmUserRoleChangeDescription: "将用户 {{user}} 的身份切换为“{{role}}”。",
        userRoleTokenNotice: "用户当前已签发的令牌可能保留旧权限；请让该用户重新登录以获取新身份。",
        userRoleUpdateSucceeded: "用户身份已更新",
        userRoleUpdateSucceededDescription: "已更新用户 {{user}} 的身份。",
        userRoleUpdateFailed: "用户身份更新失败",
        userRoleUpdateFailedDescription: "无法更新该用户身份，请稍后重试。",
        userRoleProtectedDescription: "不能降级当前登录的管理员或系统中的最后一个管理员。",
        notificationManagement: "启动器通知管理",
        notificationManagementDescription:
            "创建、编辑和删除 LauncherX 启动器通知。保存后会立即刷新服务端缓存，无需等待后台轮询。",
        notificationCount: "共 {{count}} 条通知",
        searchNotifications: "搜索标题、正文或作者",
        notification: "通知",
        notificationAuthor: "作者",
        publishDate: "发布时间",
        createNotification: "新建通知",
        editNotification: "编辑通知",
        edit: "编辑",
        notificationTitle: "通知标题",
        notificationContent: "通知正文",
        noNotifications: "暂无通知",
        launcherNotifications: "启动器通知",
        launcherNotificationsLoadFailed: "无法获取启动器通知，请检查网络连接后重试。",
        fieldRequired: "此项为必填项。",
        notificationListLoadFailed: "加载通知失败",
        notificationListLoadFailedDescription: "无法获取通知列表，请检查网络连接或管理员权限。",
        notificationSaveSucceeded: "通知已保存",
        notificationCreatedDescription: "通知已创建并立即对启动器生效。",
        notificationUpdatedDescription: "通知已更新并立即对启动器生效。",
        notificationSaveFailed: "保存通知失败",
        notificationSaveFailedDescription: "无法保存通知，请检查内容后重试。",
        confirmDeleteNotification: "确认删除通知？",
        confirmDeleteNotificationDescription: "通知“{{title}}”将被永久删除。",
        notificationDeleteSucceeded: "通知已删除",
        notificationDeleteSucceededDescription: "通知已删除，启动器缓存已同步刷新。",
        notificationDeleteFailed: "删除通知失败",
        notificationDeleteFailedDescription: "无法删除通知，它可能已经不存在。",
        contributionManagement: "资源贡献管理",
        contributionReview: "资源贡献审批",
        contributionManagementDescription:
            "管理 LauncherX 用户提交的第三方资源译名、链接、标签与评分，并将审核结果转为正式资源。",
        pendingContributionList: "待审批资源",
        pendingContributionCount: "共 {{count}} 个待审批资源",
        pendingResources: "待审批资源",
        totalSubmissions: "提交总数",
        ratedResources: "已有评分",
        contributionResource: "资源",
        submissionCount: "贡献数",
        userRating: "用户评分",
        noRating: "暂无评分",
        notTranslated: "暂无译名",
        actions: "操作",
        review: "审批",
        searchContributions: "搜索资源名称、译名或 ID",
        noPendingContributions: "暂无待审批贡献",
        contributionListLoadFailed: "加载贡献列表失败",
        contributionListLoadFailedDescription: "无法获取待审批贡献，请检查网络连接或管理员权限。",
        contributionDetail: "贡献详情",
        contributionDetailLoadFailed: "加载贡献详情失败",
        contributionDetailLoadFailedDescription: "无法获取贡献详情，请检查网络连接或管理员权限。",
        contributionNotFound: "该待审批资源不存在或已被其他管理员处理。",
        backToContributionList: "返回贡献列表",
        resourceId: "资源 ID",
        contributor: "贡献者",
        suggestedTranslation: "建议译名",
        contributedLink: "贡献链接",
        contributedTag: "贡献标签",
        translationContributions: "翻译贡献",
        translationContributionDescription:
            "查看用户提交的候选译名，采纳后自动填入下方表单，也可删除无效记录或封禁恶意提交者。",
        adoptContribution: "采纳",
        linkContributions: "链接贡献",
        tagContributions: "标签贡献",
        ratingContributions: "评分记录",
        noTranslationContributions: "暂无翻译贡献",
        noLinkContributions: "暂无链接贡献",
        noTagContributions: "暂无标签贡献",
        noRatingContributions: "暂无评分记录",
        delete: "删除",
        banUser: "封禁用户",
        confirmDeleteContribution: "确认删除贡献？",
        confirmDeleteContributionDescription: "将永久删除贡献记录 {{id}}，此操作不可撤销。",
        deleteContributionSucceeded: "贡献已删除",
        deleteContributionSucceededDescription: "该贡献记录已从待审批资源中移除。",
        deleteContributionFailed: "删除贡献失败",
        deleteContributionFailedDescription: "无法删除该贡献，它可能已经不存在。",
        confirmBanUser: "确认封禁用户？",
        confirmBanUserDescription: "用户 {{user}} 将无法继续提交第三方资源贡献。",
        banUserSucceeded: "用户已封禁",
        banUserSucceededDescription: "已封禁用户 {{user}}。",
        banUserFailed: "封禁用户失败",
        banUserFailedDescription: "无法封禁该用户，请稍后重试。",
        userAlreadyBanned: "该用户已经被封禁。",
        finalResourceInformation: "最终资源信息",
        finalResourceInformationDescription:
            "确认最终译名、链接和标签。提交后会创建正式资源、记录贡献者，并清理此资源的全部待审批记录。",
        finalTranslatedName: "最终译名",
        finalResourceLink: "最终资源链接",
        finalResourceTags: "最终资源标签",
        resourceTagsPlaceholder: "使用英文逗号分隔多个标签",
        translatedNameRequired: "请填写最终译名。",
        resourceLinkRequired: "请填写最终资源链接。",
        resourceLinkInvalid: "请输入有效的 HTTP 或 HTTPS 链接。",
        resourceTagsRequired: "请至少填写一个标签。",
        clear: "清除",
        acceptAsOfficialResource: "转为正式资源",
        confirmAcceptContribution: "确认转为正式资源？",
        confirmAcceptContributionDescription:
            "该操作会创建正式资源，记录所有相关贡献者，并删除当前资源的全部第三方提交与评分。此操作不可撤销。",
        acceptContributionSucceeded: "贡献审批完成",
        acceptContributionSucceededDescription: "待审批信息已成功转为正式资源。",
        acceptContributionFailed: "审批贡献失败",
        acceptContributionFailedDescription: "无法将贡献转为正式资源，请确认资源仍然存在并稍后重试。",
        buildManagementDescription: "仅已发布构建对外可用",
        allBuilds: "全部构建",
        buildCount: "共 {{count}} 个构建",
        buildInfo: "构建信息",
        buildTarget: "构建目标",
        buildStatus: "状态",
        pushEnabledBuilds: "已开启推送",
        cachedBuilds: "当前已缓存",
        searchBuilds: "搜索分支、框架或运行时",
        noMatchingBuilds: "没有符合条件的构建",
        releaseDate: "发布日期",
        buildBranch: "分支",
        buildChannel: "通道",
        buildFramework: "目标框架",
        buildRuntime: "运行时",
        buildReviewStatus: "审核状态",
        buildApproved: "已通过",
        buildRejected: "未通过",
        buildUnreviewed: "未审核",
        buildCacheStatus: "缓存状态",
        buildCached: "已缓存",
        buildNotCached: "未缓存",
        pushToUsers: "外网发布",
        enabled: "开启",
        disabled: "关闭",
        refreshBuildCacheNow: "刷新缓存",
        buildUpdateSucceeded: "构建已更新",
        buildEnabledDescription: "该构建已发布到外网。",
        buildDisabledDescription: "该构建已从外网撤下。",
        buildUpdateFailed: "构建更新失败",
        buildDownloadFailed: "构建下载失败",
        buildDownloadFailedDescription: "无法下载构建，请检查登录状态或稍后重试。",
        buildDownloadNotFound: "构建或构建文件已不存在，请刷新列表后重试。",
        buildUpdateFailedDescription: "无法更新构建，请稍后重试。",
        buildNoLongerExists: "该构建已被替换或清理，列表已自动刷新，请重新选择。",
        buildCacheRefreshSucceeded: "构建缓存已刷新",
        buildCacheRefreshSucceededDescription: "当前缓存包含 {{count}} 个可推送构建。",
        buildCacheRefreshFailed: "构建缓存刷新失败",
        buildCacheRefreshFailedDescription: "无法刷新构建缓存，请稍后重试。",
        query: "查询",
        querySponsorInfo: "查询赞助者信息",
        querySponsorInfoDescription:
            "该功能用于查询任意用户的简要信息，包含用户的用户名，ID，赞助信息等。这些为敏感信息，请勿泄露！",

        setUserAsSponsor: "将用户设置为赞助者",
        setUserAsSponsorDescription:
            "输入用户名或旧账户邮箱来将用户设置为赞助者。注意：请勿滥用该功能，一经发现可能会被吊销管理员权限！",

        isPaid: "已支付",
        notPay: "未支付",

        queriedSponsorInfo: "查询到的用户信息",
        redeemOrderNumber: "兑换订单号",
        redeemTime: "兑换时间",
        noRedeemRecord: "无兑换记录",
        manualSponsorGrant: "管理员手动授予",
        sponsoredUsers: "已赞助用户",
        sponsorCount: "共 {{count}} 位赞助用户",
        searchSponsors: "搜索用户名、邮箱或用户 ID",
        noSponsors: "没有符合条件的赞助用户",
        sponsorListLoadFailed: "加载赞助用户失败",
        sponsorListLoadFailedDescription: "无法获取赞助用户列表，请检查网络连接或管理员权限。",
        copyOrderNumber: "复制兑换订单号",
        orderNumberCopied: "订单号已复制",

        copy: "复制",

        setSponsorFailed: "设置赞助者失败",
        setSponsorSucceeded: "成功设置赞助者",
        setSponsorSucceededDescription: "成功将用户设置为赞助者，该操作已被记录。",
        noRecommendedBuild: "没有推荐的版本",
        failedToLoadBuildsDescription: "无法加载版本信息，请稍后重试。",
        failedToLoadBuilds: "无法加载版本信息",
        retry: "重试",

        downloadThanks: "感谢您的下载",
        downloadThanksDescription: "您的下载应该已经开始。如果遇到问题，请查阅下方的设置指南。",
        downloadThanksFollowGuide: "请按照下面的设置指南完成安装。",
        setupGuides: "设置指南",
        recommendedGuide: "推荐指南",
        basedOnYourSystem: "根据您的操作系统",
        weRecommendReading: "我们建议您阅读",
        windowsSetupGuide: "Windows 设置指南",
        macosSetupGuide: "macOS 设置指南",
        linuxSetupGuide: "Linux 设置指南",

        guideFor: "适用于",
        viewGuide: "查看指南",
        revokeCsAccountTitle: "彻底删除日冕账号以及与之相关的所有数据",
        revokeCsAccountMessage:
            "该操作会删除您的一切有关数据，包括您的账号信息，设备信息，赞助信息，好友关系，与好友的全部聊天内容（双向）。该操作不可恢复，请谨慎操作！",
        logoutAndDelete: "注销并删除",

        confirmDelete: "确认删除?",
        deleteAccountFailed: "删除账号失败",
        deleteAccountFailedDescription1:
            "删除账号失败，用户凭据已失效，请尝试重新登录后再试，如果持续出现错误，请联系系统管理员。",
        deleteAccountFailedDescription2: "删除账号失败，请稍后重试或联系系统管理员，疑似后端服务器故障。",

        deleteAccountSucceeded: "删除账号成功",
        deleteAccountSucceededDescription:
            "删除账号成功，您的账号信息已经被删除，您将无法再使用该账号登录日冕工作室的任何服务。期待与您的再次相遇。",

        sponsorBadgeText: "荣誉股东",
        talkIsCheap: "闲话少说"
    }
};
